# Generated by Django 4.2.23 on 2025-12-13 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='party',
            constraint=models.UniqueConstraint(fields=('trn', 'type'), name='unique_trn_per_type'),
        ),
    ]
