# Generated by Django 4.2.23 on 2025-11-29 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_extracharges'),
    ]

    operations = [
        migrations.AddField(
            model_name='extracharges',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extracharges',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
