# Generated by Django 4.2.23 on 2025-12-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_extracharges_description_extracharges_vat'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensetype',
            name='category',
            field=models.CharField(choices=[('direct', 'Direct'), ('indirect', 'Indirect')], default='indirect', help_text='Direct or Indirect expense', max_length=10),
        ),
    ]
