# Generated by Django 4.2.23 on 2025-12-20 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_party_unique_trn_per_type'),
        ('common', '0008_assetsale'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetsale',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_sales', to='customer.party'),
        ),
        migrations.AddField(
            model_name='assetsale',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
