# Generated by Django 4.2.23 on 2025-11-09 08:31

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'Payment In Progress'), ('approved', 'Approved'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], default='pending', max_length=20)),
                ('purchase_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('vat_amount_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_with_vat_usd', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('vat_amount_aed', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_with_vat_aed', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('discount_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('discount_aed', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('outside_or_inside', models.CharField(choices=[('inside', 'Inside'), ('outside', 'Outside')], default='inside', max_length=20)),
                ('has_tax', models.BooleanField(default=True)),
                ('custom_duty_aed', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('custom_duty_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('has_custom_duty', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_invoices', to='customer.party')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField()),
                ('sold_qty', models.PositiveIntegerField(default=0)),
                ('unit_price_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price_aed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipping_per_unit_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shipping_per_unit_aed', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('factors', models.CharField(blank=True, max_length=100, null=True)),
                ('amount_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_aed', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_items', to='purchase.purchaseinvoice')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productitem')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tax', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='common.tax')),
            ],
        ),
    ]
