# Generated by Django 4.2.23 on 2025-11-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='currency',
            field=models.CharField(default='AED', max_length=3),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='currency_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
