# Generated by Django 4.2.23 on 2025-11-12 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_purchaseinvoice_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_items', to='purchase.purchaseinvoice'),
        ),
    ]
