# Generated by Django 4.2.23 on 2025-11-16 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_purchasereturnitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
