# Generated by Django 4.2.23 on 2025-11-18 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_asset'),
        ('purchase', '0005_purchaseitem_vat_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='common.tax'),
        ),
    ]
