# Generated by Django 4.2.23 on 2025-11-20 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0006_alter_purchaseitem_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='custom_duty_aed_enter',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='custom_duty_usd_enter',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
