# Generated by Django 4.2.23 on 2025-11-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0007_purchaseinvoice_custom_duty_aed_enter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='custom_duty_aed_enter',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='custom_duty_usd_enter',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
