# Generated by Django 4.2.23 on 2025-11-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0008_purchaseitem_custom_duty_aed_enter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='shipping_total_aed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='shipping_total_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
