# Generated by Django 4.2.23 on 2025-11-26 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0009_purchaseitem_shipping_total_aed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='custom_duty_aed_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='custom_duty_usd_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
