# Generated by Django 4.2.23 on 2025-11-27 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0010_purchaseitem_custom_duty_aed_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='total_price_aed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='total_price_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='vat_per_unit_aed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='vat_per_unit_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='vat_total_aed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='vat_total_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
