# Generated by Django 4.2.23 on 2025-12-01 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0011_purchaseitem_total_price_aed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='is_payment_started',
            field=models.BooleanField(default=False),
        ),
    ]
