# Generated by Django 4.2.23 on 2025-12-01 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0012_purchaseinvoice_is_payment_started'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasereturnitem',
            name='purchase_item',
        ),
        migrations.RemoveField(
            model_name='purchasereturnitem',
            name='qty',
        ),
        migrations.CreateModel(
            name='PurchaseReturnItemEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('purchase_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.purchaseitem')),
                ('purchase_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='purchase.purchasereturnitem')),
            ],
        ),
    ]
