# Generated by Django 4.2.23 on 2025-12-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_extrapurchase'),
        ('purchase', '0013_remove_purchasereturnitem_purchase_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='extra_purchases',
            field=models.ManyToManyField(blank=True, related_name='purchase_invoices', to='common.extrapurchase'),
        ),
    ]
