# Generated by Django 4.2.23 on 2025-11-09 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_in_hand', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cash_in_bank', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('check_cash', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('type', models.CharField(choices=[('main', 'Main'), ('profit', 'Profit')], default='main', max_length=20, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_type', models.CharField(choices=[('sale', 'Sale'), ('purchase', 'Purchase')], help_text='Type of invoice this payment belongs to', max_length=10)),
                ('invoice_id', models.PositiveIntegerField(help_text='ID of related Sale or Purchase invoice')),
                ('payment_type', models.CharField(choices=[('hand', 'Cash'), ('bank', 'Bank'), ('check', 'Check')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Payment Entries',
            },
        ),
    ]
