# Generated by Django 4.2.23 on 2025-11-16 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymententry',
            name='charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
