# Generated by Django 4.2.23 on 2025-11-16 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('banking', '0002_paymententry_charges'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymententry',
            name='party',
            field=models.ForeignKey(blank=True, help_text='Customer or Supplier for this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.party'),
        ),
    ]
