# Generated by Django 4.2.23 on 2025-12-01 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_paymententry_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymententry',
            name='cheque_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
