# Generated by Django 4.2.23 on 2025-12-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0004_paymententry_cheque_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymententry',
            name='payment_date',
            field=models.DateField(blank=True, help_text='Date of payment', null=True),
        ),
    ]
