# Generated by Django 4.2.23 on 2025-12-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0005_paymententry_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymententry',
            name='is_cheque_cleared',
            field=models.BooleanField(default=False),
        ),
    ]
