# Generated by Django 4.2.23 on 2025-12-07 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('banking', '0006_paymententry_is_cheque_cleared'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashAccountTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_type', models.CharField(choices=[('cash_in_hand', 'Cash in Hand'), ('cash_in_bank', 'Cash in Bank'), ('cash_in_check', 'Check Cash')], max_length=20)),
                ('to_type', models.CharField(choices=[('cash_in_hand', 'Cash in Hand'), ('cash_in_bank', 'Cash in Bank'), ('cash_in_check', 'Check Cash')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='banking.cashaccount')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='banking.cashaccount')),
            ],
            options={
                'verbose_name_plural': 'Cash Account Transfers',
            },
        ),
    ]
