# Generated by Django 4.2.23 on 2025-12-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0007_cashaccounttransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymententry',
            name='cheque_cleared_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
