# Generated by Django 4.2.23 on 2025-12-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0008_paymententry_cheque_cleared_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashaccounttransfer',
            name='transfer_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
