# Generated by Django 4.2.23 on 2025-10-24 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='sold_qty',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
