# Generated by Django 4.2.23 on 2025-09-28 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('amount_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_aed', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sales_invoice', models.ForeignKey(blank=True, help_text='Optional: Associated sales invoice', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_fees', to='base.saleinvoice')),
            ],
        ),
    ]
