# Generated by Django 4.2.23 on 2025-09-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_servicefee'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='is_shown',
            field=models.BooleanField(default=False),
        ),
    ]
