# Generated by Django 4.2.23 on 2025-08-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_tax_purchase_total_with_vat_purchase_vat_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='total_with_vat',
            new_name='total_with_vat_aed',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='vat_amount',
            new_name='vat_amount_aed',
        ),
        migrations.RenameField(
            model_name='saleinvoice',
            old_name='total_with_vat',
            new_name='total_with_vat_aed',
        ),
        migrations.RenameField(
            model_name='saleinvoice',
            old_name='vat_amount',
            new_name='vat_amount_aed',
        ),
        migrations.AddField(
            model_name='purchase',
            name='total_with_vat_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
        ),
        migrations.AddField(
            model_name='purchase',
            name='vat_amount_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='total_with_vat_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='vat_amount_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
