# Generated by Django 4.2.23 on 2025-10-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_cashaccount_account_created_at_account_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'Payment In Progress'), ('approved', 'Approved'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'Payment In Progress'), ('approved', 'Approved'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], default='pending', max_length=20),
        ),
    ]
