# Generated by Django 4.2.23 on 2025-08-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_total_with_vat_purchase_total_with_vat_aed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='sale_price_aed',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
