# Generated by Django 4.2.23 on 2025-10-11 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0005_alter_purchaseinvoice_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('amount_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_aed', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], default='debit', max_length=25)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='account',
        ),
        migrations.RenameField(
            model_name='cashaccount',
            old_name='balance',
            new_name='cash_in_bank',
        ),
        migrations.RemoveField(
            model_name='cashaccount',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='cashaccount',
            name='name',
        ),
        migrations.AddField(
            model_name='cashaccount',
            name='cash_in_hand',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='cashaccount',
            name='check_cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='outside_or_inside',
            field=models.CharField(choices=[('inside', 'Inside'), ('outside', 'Outside')], default='inside', max_length=20),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='outside_or_inside',
            field=models.CharField(choices=[('inside', 'Inside'), ('outside', 'Outside')], default='inside', max_length=20),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='purchase_item',
            field=models.ForeignKey(blank=True, help_text='The purchase item this sale item is sourced from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_items', to='base.purchaseitem'),
        ),
        migrations.DeleteModel(
            name='AccountTransfer',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.AddField(
            model_name='commission',
            name='sales_invoice',
            field=models.ForeignKey(blank=True, help_text='Optional: Associated sales invoice', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='base.saleinvoice'),
        ),
    ]
