# Generated by Django 4.2.23 on 2025-10-11 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_commission_remove_transaction_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('product_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='base.productitem')),
            ],
        ),
    ]
