# Generated by Django 4.2.23 on 2025-08-30 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_designation_account_designation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salaryentry',
            old_name='amount',
            new_name='amount_aed',
        ),
        migrations.AddField(
            model_name='salaryentry',
            name='amount_usd',
            field=models.DecimalField(decimal_places=2, default=123, max_digits=12),
            preserve_default=False,
        ),
    ]
