# Generated by Django 4.2.23 on 2025-10-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='has_tax',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='has_tax',
            field=models.BooleanField(default=True),
        ),
    ]
