# Generated by Django 4.2.23 on 2025-08-30 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rename_amount_salaryentry_amount_aed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='amount',
            new_name='amount_aed',
        ),
        migrations.AddField(
            model_name='expense',
            name='amount_usd',
            field=models.DecimalField(decimal_places=2, default=345, max_digits=12),
            preserve_default=False,
        ),
    ]
