# Generated by Django 4.2.23 on 2025-10-11 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_purchaseinvoice_has_tax_saleinvoice_has_tax'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(choices=[('customer', 'Customer'), ('supplier', 'Supplier')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='saleinvoice',
            name='customer_name',
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_invoices', to='base.party'),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_invoices', to='base.party'),
        ),
    ]
