# Generated by Django 4.2.23 on 2025-09-04 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_rename_amount_expense_amount_aed_expense_amount_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='amount_aed',
            field=models.DecimalField(decimal_places=2, default=12, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='amount_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
