# Generated by Django 4.2.23 on 2025-09-04 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_saleitem_amount_aed_alter_saleitem_amount_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='shipping_aed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='shipping_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
