# Generated by Django 4.2.23 on 2025-10-12 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_employeeleave'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleinvoice',
            name='is_sales_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='status',
            field=models.CharField(choices=[('sales_team_pending', 'Sales Team Pending (Proforma)'), ('sales_team_approved', 'Sales Team Approved (Proforma)'), ('pending', 'Pending'), ('in_progress', 'Payment In Progress'), ('approved', 'Approved'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], default='sales_team_pending', max_length=30),
        ),
    ]
