# Generated by Django 4.2.23 on 2025-09-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_saleitem_shipping_aed_saleitem_shipping_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
