# Generated by Django 4.2.23 on 2025-10-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_saleinvoice_is_sales_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymententry',
            name='payment_type',
            field=models.CharField(choices=[('hand', 'Cash'), ('bank', 'Bank'), ('check', 'Check')], max_length=10),
        ),
    ]
