# Generated by Django 4.2.23 on 2025-09-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_purchase_invoice_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='invoice_no',
            field=models.CharField(default=12, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
