# Generated by Django 4.2.23 on 2025-09-08 14:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_purchase_invoice_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=50, unique=True)),
                ('supplier', models.CharField(blank=True, max_length=100, null=True)),
                ('purchase_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('vat_amount_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_with_vat_usd', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('vat_amount_aed', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_with_vat_aed', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField()),
                ('unit_price_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price_aed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipping_per_unit_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shipping_per_unit_aed', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('factors', models.CharField(blank=True, max_length=100, null=True)),
                ('amount_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_aed', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_items', to='base.purchaseinvoice')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.productitem')),
            ],
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
