# Generated by Django 4.2.23 on 2025-10-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_expense_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryentry',
            name='payment_type',
            field=models.CharField(choices=[('hand', 'Cash'), ('bank', 'Bank'), ('check', 'Check')], default='hand', max_length=25),
        ),
    ]
