# Generated by Django 4.2.23 on 2025-10-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_salaryentry_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashaccount',
            name='type',
            field=models.CharField(choices=[('main', 'Main'), ('profit', 'Profit')], default='main', max_length=20, unique=True),
        ),
    ]
