# Generated by Django 4.2.23 on 2025-09-09 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_purchaseinvoice_purchaseitem_delete_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='tax',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='base.tax'),
            preserve_default=False,
        ),
    ]
