# Generated by Django 4.2.23 on 2025-09-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_purchaseitem_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='productitem',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
