# Generated by Django 4.2.23 on 2025-09-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_productitem_created_at_productitem_modified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleinvoice',
            name='discount_aed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='discount_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
