# Generated by Django 4.2.23 on 2025-09-21 09:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_saleinvoice_discount_aed_saleinvoice_discount_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='discount_aed',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='discount_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
    ]
