# Generated by Django 4.2.23 on 2025-09-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_purchaseinvoice_discount_aed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='is_reminder_needed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expense',
            name='reminder_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
