# Generated by Django 4.2.23 on 2025-11-09 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
        ('customer', '0001_initial'),
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('sales_team_pending', 'Sales Team Pending (Proforma)'), ('sales_team_approved', 'Sales Team Approved (Proforma)'), ('payment_pending', 'Payment Pending'), ('payment_in_progress', 'Payment In Progress'), ('approved', 'Approved'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], default='sales_team_pending', max_length=30)),
                ('is_sales_approved', models.BooleanField(default=False)),
                ('sale_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('vat_amount_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_with_vat_usd', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('vat_amount_aed', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_with_vat_aed', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('discount_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_aed', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('outside_or_inside', models.CharField(choices=[('inside', 'Inside'), ('outside', 'Outside')], default='inside', max_length=20)),
                ('has_tax', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_invoices', to='customer.party')),
            ],
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField()),
                ('sale_price_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_price_aed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_aed', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('shipping_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('shipping_aed', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_items', to='sale.saleinvoice')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productitem')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('purchase_item', models.ForeignKey(blank=True, help_text='The purchase item this sale item is sourced from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_items', to='purchase.purchaseitem')),
            ],
        ),
    ]
