# Generated by Django 4.2.23 on 2025-11-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleinvoice',
            name='biller_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
