# Generated by Django 4.2.23 on 2025-11-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_saleinvoice_biller_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='amount_aed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
