# Generated by Django 4.2.23 on 2025-11-15 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0004_salereturnitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleinvoice',
            name='status',
            field=models.CharField(choices=[('sales_team_pending', 'Sales Team Pending (Proforma)'), ('sales_team_approved', 'Sales Team Approved (Proforma)'), ('pending', 'Pending'), ('payment_in_progress', 'Payment In Progress'), ('approved', 'Approved'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], default='sales_team_pending', max_length=30),
        ),
    ]
