# Generated by Django 4.2.23 on 2025-11-16 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0005_alter_saleinvoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='delivery_status',
            field=models.CharField(choices=[('delivered', 'Delivered'), ('not_delivered', 'Not Delivered')], default='not_delivered', max_length=20),
        ),
    ]
