# Generated by Django 4.2.23 on 2025-11-16 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sale', '0007_saleitem_vat_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DO_id', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sale_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_notes', to='sale.saleinvoice')),
                ('sale_items', models.ManyToManyField(related_name='delivery_notes', to='sale.saleitem')),
            ],
        ),
    ]
