# Generated by Django 4.2.23 on 2025-11-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0008_deliverynote'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleinvoice',
            name='perfoma_invoice_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='quotation_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
