# Generated by Django 4.2.23 on 2025-11-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0009_saleinvoice_perfoma_invoice_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleinvoice',
            name='tax_invoice_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deliverynote',
            name='DO_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
