# Generated by Django 4.2.23 on 2025-11-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0011_saleitem_total_price_aed_saleitem_total_price_usd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleinvoice',
            name='invoice_no',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
