# Generated by Django 4.2.23 on 2025-11-27 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0012_alter_saleinvoice_invoice_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleinvoice',
            old_name='tax_invoice_number',
            new_name='purchase_order_number',
        ),
    ]
