# Generated by Django 4.2.23 on 2025-12-01 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0013_rename_tax_invoice_number_saleinvoice_purchase_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleinvoice',
            name='is_payment_started',
            field=models.BooleanField(default=False),
        ),
    ]
