# Generated by Django 4.2.23 on 2025-12-01 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0014_saleinvoice_is_payment_started'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salereturnitem',
            name='qty',
        ),
        migrations.RemoveField(
            model_name='salereturnitem',
            name='sale_item',
        ),
        migrations.CreateModel(
            name='SaleReturnItemEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('sale_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.saleitem')),
                ('sale_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='sale.salereturnitem')),
            ],
        ),
    ]
