# Generated by Django 4.2.23 on 2025-12-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0015_remove_salereturnitem_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleinvoice',
            name='sale_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
