# Generated by Django 4.2.23 on 2025-12-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0016_saleinvoice_sale_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleinvoice',
            name='payment_method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
