# Generated by Django 4.2.23 on 2025-11-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='weight_kg_each',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
